### ISSUE TITLE
how to get the timeid ?

### ISSUE THREAD

**Issue by syu-lk4b** [fireyy/my-laser-egg#1]
this is really cool man, question of how to get the timeId? and do you know have any plan put this into homebridge ,so it can check from IOS homekit. that will be so cool. if you dont have any plan, i would like to try it. but can you provide some help?

thanks, you da man

**Comment by fireyy** [comment]
You can find the TimeID in the [official app](http://originstech.com/products/breathingspaceapp).
There is no plan to put this into homebridge now. May be later :)

**Comment by syu-lk4b** [comment]
I am using iPhone, from the app, i don't see the timeId in any setting. is this from Andorid app? I know andorid always give more freedom.

**Comment by fireyy** [comment]
They redesign the app, I will check if any way to get the timeID soon

**Comment by syu-lk4b** [comment]
thanks dude

**Comment by fireyy** [comment]
I checked the app, and the timeId was no longer shown. The easiest way is to use [charles](https://www.charlesproxy.com/) or similar tools to capture the network request to get timeId.

**Comment by syu-lk4b** [comment]
Thanks so much,I'll try this weekend. Much appreciate your reply and helps

**Comment by syu-lk4b** [comment]
checked the code, not sure how you get the AQI from the device, can you explain a little bit?

**Comment by fireyy** [comment]
The Laser egg will upload data to their server, so we get the data from their api with device timeId

**Comment by fireyy** [comment]
I update the README for get the timeId, b519ad9c28c7a057ba6afd1e477abf00d736414a

**Comment by syu-lk4b** [comment]
thanks man
